apiVersion: v1
kind: Secret
metadata:
    name: github-deployer-token
    namespace: kube-system
    annotations:
        kubernetes.io/service-account.name: github-deployer
type: kubernetes.io/service-account-token
