apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-cluster-secret-store
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:heung115/tmp-onebite-gitops.git
    targetRevision: eks
    path: eks/cicd/cluster-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
