apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: backend-dev-back
    namespace: argocd
spec:
    project: default
    sources:
        - repoURL: git@github.com:heung115/tmp-onebite-gitops.git
          targetRevision: main
          path: charts/backend
          helm:
              releaseName: backend-dev-back
              valueFiles:
                  - values.yaml
                  - $values/envs/common-backend.yaml
                  - $values/envs/dev-back/backend.yaml
        - repoURL: git@github.com:heung115/tmp-onebite-gitops.git
          targetRevision: main
          ref: values
          path: envs/dev-back
          directory:
              include: external-secret.yaml
    destination:
        server: https://kubernetes.default.svc
        namespace: dev-back
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
