apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.web-env.name" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  {{- if .Values.web.extraEnvs }}
  {{- range $index, $map := .Values.web.extraEnvs }}
  {{ $map.name | upper | replace "-" "_" }}: {{ $map.value | toString | b64enc | quote }}
  {{- end }}
  # .env.local: 
  #   {{- $envStr := "" }}
  #   {{- range $index, $map := .Values.web.extraEnvs }}
  #   {{- $key := $map.name | upper | replace "-" "_" }}
  #   {{- $envStr = printf "%s%s=%s\n" $envStr $key $map.value }}
  #   {{- end }}
  #   {{ $envStr | b64enc }}
  # {{- end }}