apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-dev-front-secret
  namespace: dev-front
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onebite-aws
  target:
    name: backend-dev-front-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: backend-dev-front
